/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 1facc55370f483f398e8a47cfb9f1879)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/index");
		durableNamespaces: "SixtyAgent";
	}
	interface Env {
		SixtyAgent: DurableObjectNamespace /* SixtyAgent */;
	}
}
interface Env extends Cloudflare.Env {}
